# Generated by Django 5.1 on 2024-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("grade", models.CharField(max_length=255, verbose_name="grade")),
                (
                    "curse_name",
                    models.CharField(max_length=255, verbose_name="curse name"),
                ),
                ("sources", models.CharField(max_length=255, verbose_name="sources")),
                (
                    "difficulty_level",
                    models.CharField(max_length=255, verbose_name="difficulty level"),
                ),
                ("starting_date", models.DateTimeField(verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                (
                    "negative_point",
                    models.BooleanField(default=False, verbose_name="negative point"),
                ),
                (
                    "is_enable",
                    models.BooleanField(default=False, verbose_name="is enable"),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
            ],
            options={
                "verbose_name": "exam",
                "verbose_name_plural": "exams",
            },
        ),
        migrations.CreateModel(
            name="GeneralCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "category_type",
                    models.CharField(max_length=255, verbose_name="type"),
                ),
                (
                    "description",
                    models.CharField(max_length=400, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "GeneralCategory",
                "verbose_name_plural": "GeneralCategories",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="question")),
                ("option1", models.CharField(max_length=255, verbose_name="option1")),
                ("option2", models.CharField(max_length=255, verbose_name="option2")),
                ("option3", models.CharField(max_length=255, verbose_name="option3")),
                ("option4", models.CharField(max_length=255, verbose_name="option4")),
                (
                    "right_option",
                    models.CharField(max_length=255, verbose_name="right option"),
                ),
                ("suggested_time", models.TimeField(verbose_name="time")),
                ("score", models.IntegerField(verbose_name="score")),
                ("level", models.CharField(max_length=255, verbose_name="level")),
                (
                    "is_enable",
                    models.BooleanField(default=False, verbose_name="is enable"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="crated time"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="updated time"),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.CharField(max_length=400, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
            },
        ),
    ]
