# Generated by Django 5.1 on 2024-08-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="auther",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auther",
                to=settings.AUTH_USER_MODEL,
                verbose_name="auther",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="general_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.generalcategory",
                verbose_name="general category",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.subcategory",
                verbose_name="category",
            ),
        ),
    ]
